samples: config/samples.tsv
units: config/units.tsv

##########################################################
#  FOR A COMMENTED VERSION OF THIS CONFIGURATION FILE,   #
#  PLEASE SEE THE MAIN `config/config.yaml` FILE         #
##########################################################

experiment:
  3-prime-rna-seq:
    activate: true
    vendor: lexogen
    plot-qc: all

resources:
  ref:
    species: homo_sapiens
    release: "114"
    build: GRCh38
    pfam: "37.0"
    representative_transcripts: canonical
  ontology:
    gene_ontology: "https://release.geneontology.org/2025-07-22/ontology/go-basic.obo"

pca:
  exclude_nas: false
  labels:
    - condition

scatter:
  activate: true

diffexp:
  exclude:
  models:
    model_X:
      full: ~condition
      reduced: ~1
      primary_variable: condition
      base_level: Control
  sig-level:
    volcano-plot: 0.05
    ma-plot: 0.05
    qq-plot: 0.05
  genes_of_interest:
    activate: false
    genelist: "resources/gene_list.tsv"

diffsplice:
  activate: false
  coding_cutoff: 0.725
  remove_noncoding_orfs: false
  fdr: 1.0
  min_effect_size: 0.0

enrichment:
  goatools:
    activate: true
    fdr_genes: 0.05
    fdr_go_terms: 0.05
  fgsea:
    activate: true
    gene_sets_file: "config/gene_sets.gmt"
    fdr_gene_set: 0.05
    eps: 0.0001
  spia:
    activate: true
    pathway_databases:
      - panther

meta_comparisons:
  activate: false
  comparisons:
    treated_vs_untreated_against_other_model:
      items:
        treatead_vs_untreated: treated_vs_untreated
        Y: model_Y
      label: treated_vs_untreated compared to other_model

bootstrap_plots:
  FDR: 0.01
  top_n: 3
  color_by: condition

plot_vars:
  sig_level: 0.1

params:
  kallisto: "-b 30"
