samples: samples.tsv
units: units.tsv

# the sequencing adapter
adapter: "ACGGATCGATCGATCGATCGAT"

ref:
  transcriptome: "data/ref/Mus_musculus.GRCm38.cdna.all.plus_RUNX1a_GFP.fa"
  # species needs to be an identifier known to biomart, e.g. mmusculus, hsapiens
  species: mmusculus
  # gene ontology to download, used e.g. in goatools
  gene_ontology: "http://current.geneontology.org/ontology/go-basic.obo"

pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # samples to exclude (e.g. outliers due to technical problems)
  exclude:
  # model for sleuth differential expression analysis
  models:
    model_X: 
      full: ~condition + batch_effect
      reduced: ~batch_effect
      # Binary valued covariate that shall be used for fold change/effect size
      # based downstream analyses.
      primary_variable: condition

enrichment:
  gene_sets_file: "data/ref/gene_sets_of_interest.gmt"
  goatools:
    fdr_genes: 0.05
    fdr_go_terms: 0.05
  fgsea:
    fdr_gene_set: 0.05
    nperm: 100000

bootstrap_plots:
  # desired false discovery rate for bootstrap plots, i.e. a lower FDR will result in fewer boxplots generated
  FDR: 0.01
  # maximum number of bootstrap plots to generate, i.e. top n discoveries to plot
  top_n: 20
  color_by: condition
  # for now, this will plot the sleuth-normalised kallisto count estimations with kallisto
  # for all the transcripts of the respective genes
  genes_of_interest:
    - A4galt

params:
  kallisto: "-b 100"
  # these cutadapt parameters need to contain the required flag(s) for
  # the type of adapter(s) to trim, i.e.:
  # * https://cutadapt.readthedocs.io/en/stable/guide.html#adapter-types
  #   * `-a` for 3' adapter in the forward reads
  #   * `-g` for 5' adapter in the forward reads
  #   * `-b` for adapters anywhere in the forward reads
  # also, separate capitalised letter flags are required for adapters in
  # the reverse reads of paired end sequencing:
  # * https://cutadapt.readthedocs.io/en/stable/guide.html#trimming-paired-end-reads
  cutadapt-se: ""
  cutadapt-pe: "-g GGATCGATCGATCGATCGAT -A ACGGATCGATCGATCGATCGAT -G GGATCGATCGATCGATCGAT --minimum-length 33 -e 0.005 --overlap 7"
