name: ?f"Differential expression analysis for model {wildcards.model}"
datasets:
  genes_representative:
    path: ?input.genes_representative
    separator: "\t"
views:
  genes_representative:
    dataset: genes_representative
    desc: |
      Differentially expressed transcripts computed with sleuth. The columns `b_*` and `b_*_se` display the effect size `:math:\beta` and the corresponding standard error for every covariate in the model. They are analog to log2 fold changes. Note that non-binary covariates are binarized by sleuth, leading  to multiple columns `b_*1`, `b_*2`, etc. In addition, a signed version of the pi-value score (as proposed  by `Xiao et al. 2014 <https://dx.doi.org/10.1093/bioinformatics/`) is shown. The sign reflects the sign of the effect (i.e. positive for   upregulation, negative for downregulation).
    page-size: 25
    render-table:
      columns:
        ens_gene:
          display-mode: hidden       
        ext_gene:
          display-mode: normal
        gene_desc:
          display-mode: normal
        canonical:
          display-mode: normal
          plot:
            heatmap:
              scale: ordinal
              domain:
                - TRUE
                - FALSE
              range:
                - "#aec7e8"
                - white
              custom-content: |
                function(value, row) {
                    if(value == "TRUE") {
                        return "yes"
                    } else {
                        return ""
                    }
                }
        target_id:
          display-mode: normal
          link-to-url: "http://www.ensembl.org/Homo_sapiens/Gene/Summary?g={target_id}"
        pval:
          plot:
            bars:
              scale: linear
              domain:
                - 0.000000000000000000000000000000001 
                - 0.0001
        qval:
          plot:
            bars:
              scale: linear
              domain:
                - 0.000000000000000000000000000000001 
                - 0.0001
        test_stat:
          display-mode: hidden 
        rss:
          display-mode: hidden   
        degrees_free:
          display-mode: hidden
        mean_obs:
          display-mode: hidden
        var_obs:
          display-mode: hidden
        tech_var:
          display-mode: hidden
        sigma_sq:
          display-mode: hidden
        smooth_sigma_sq:
          display-mode: hidden
        final_sigma_sq:
          display-mode: hidden
        regex('qval_.+'):
          display-mode: hidden
        regex('b_.*'):
          display-mode: normal
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -1
                - 0
                - 1
        regex('signed_pi_value_.+'):
          display-mode: hidden
        ?for samples in params.samples:
          ?samples:
            display-mode: hidden
