__use_yte__: true
max-in-memory-rows: 42000

name: ?f"Differential expression analysis for model {wildcards.model}"
datasets:
  genes_representative:
    path: ?input.genes_representative
    offer-excel: ?params.offer_excel
    links:
      link to transcripts:
        column: ens_gene
        table-row: transcripts/ens_gene
      link to log-count matrix:
        column: target_id
        table-row : logcount_matrix/transcript
      link to tpm matrix:
        column: target_id
        table-row: tpm_matrix/transcript
      link to genes representative:
        column: ens_gene
        table-row: genes_representative/ens_gene
      link to volcano plot:
        column: ens_gene
        view: volcano-plots
    separator: "\t"
  transcripts:
    path: ?input.transcripts
    offer-excel: ?params.offer_excel
    separator: "\t"
    links:
      link to log-count matrix:
        column: target_id
        table-row : logcount_matrix/transcript
      link to tpm matrix:
        column: target_id
        table-row: tpm_matrix/transcript
  genes_aggregated:
    path: ?input.genes_aggregated
    offer-excel: ?params.offer_excel
    separator: "\t"
  logcount_matrix:
    path: ?input.logcount_matrix
    offer-excel: ?params.offer_excel
    links:  
      link to transcripts:
        column: transcript
        table-row: transcripts/target_id
        optional: true
    separator: "\t"
  tpm_matrix:
    path: ?input.tpm_matrix
    offer-excel: ?params.offer_excel
    links:
      link to transcripts:
        column: transcript
        table-row: transcripts/target_id
        optional: true
    separator: "\t"
default-view: genes_representative
views:
  genes_representative:
    dataset: genes_representative
    desc: |
      Differentially expressed genes using the model computed with sleuth by taking only a manually configured representative transcript for each gene.
      The columns `b_*` and `b_*_se` display the effect size β and the corresponding standard error for every covariate in the model. They are analog to log2 fold changes. Note that non-binary covariates are binarized by sleuth, leading to multiple columns `b_*1`, `b_*2`, etc.
      The table is sorted in descending order by the absolute values of the signed versions of the pi-value score of the primary variable of model under consideration (as proposed  by `Xiao et al. 2014 <https://dx.doi.org/10.1093/bioinformatics/`). The sign reflects the sign of the effect (i.e. positive for upregulation, negative for downregulation).
    page-size: 25
    render-table:
      columns:
        ens_gene:
          display-mode: hidden       
        ext_gene:
          display-mode: normal
        gene_desc:
          display-mode: normal
        canonical:
          display-mode: normal
          plot:
            heatmap:
              scale: ordinal
              domain:
                - TRUE
                - FALSE
              range:
                - "#aec7e8"
                - white
              custom-content: |
                function(value, row) {
                    if(value == "TRUE") {
                        return "yes"
                    } else {
                        return ""
                    }
                }
        target_id:
          display-mode: normal
          link-to-url: 
            Ensembl:
              url: "http://www.ensembl.org/Homo_sapiens/Gene/Summary?g={target_id}"
        pval:
          plot:
            heatmap:
              scale: linear
              range:
                - "#a1d99b"
                - "white"
                - "#fdae6b"
              domain:
                - 0
                - 0.05
                - 0.25
        qval:
          plot:
            heatmap:
              scale: linear
              range:
                - "#a1d99b"
                - "white"
                - "#fdae6b"
              domain:
                - 0
                - 0.05
                - 0.25
        chromosome_name:
          optional: true
          display-mode: hidden
        main_transcript_per_gene:
          optional: true
          display-mode: hidden
        ensembl_transcript_id_version:
          optional: true
          display-mode: hidden
        test_stat:
          display-mode: hidden 
        rss:
          display-mode: hidden   
        degrees_free:
          display-mode: hidden
        mean_obs:
          display-mode: hidden
        var_obs:
          display-mode: hidden
        tech_var:
          display-mode: hidden
        sigma_sq:
          display-mode: hidden
        smooth_sigma_sq:
          display-mode: hidden
        final_sigma_sq:
          display-mode: hidden
        regex('qval_.+'):
          display-mode: hidden
        ?f"regex('signed_pi_value_{params.primary_variable}.+')":
          display-mode: normal
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -1
                - 0
                - 1
        ?f"regex('signed_pi_value_(?!{params.primary_variable})')":
          display-mode: hidden # Hide all signed pi cols that are not associated to the primary variable
        ?f"regex('^b_(?!.*_se$)')":
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -10
                - 0
                - 10
        regex('^b_.*_se$'):
          display-mode: hidden
        ?for sample in params.samples:
          ?sample:
            display-mode: hidden
  volcano-plots:
    dataset: genes_representative
    desc: |
      Interactive volcano plot of differentially expressed genes
    render-plot:
      spec-path: ?input.volcano_plots  
  transcripts:
    dataset: transcripts
    desc: |
      Differentially expressed transcripts using the model and computed with sleuth. The columns `b_*` and `b_*_se` display the effect size β and the corresponding standard error for every covariate in the model. They are analog to log2 fold changes. Note that non-binary covariates are binarized by sleuth, leading to multiple columns `b_*1`, `b_*2`, etc. The table is sorted in descending order by the absolute values of the signed versions of the pi-value score (as proposed  by `Xiao et al. 2014 <https://dx.doi.org/10.1093/bioinformatics/`). The sign reflects the sign of the effect (i.e. positive for upregulation, negative for downregulation).
    page-size: 25
    render-table:
      columns:
        ens_gene:
          display-mode: hidden       
        ext_gene:
          display-mode: normal         
        gene_desc:
          display-mode: normal
        canonical:
          display-mode: normal
          plot:
            heatmap:
              scale: ordinal
              domain:
                - TRUE
                - FALSE
              range:
                - "#aec7e8"
                - white
              custom-content: |
                function(value, row) {
                    if(value == "TRUE") {
                        return "yes"
                    } else {
                        return ""
                    }
                }
        target_id:
          display-mode: normal
          link-to-url: 
            Ensembl:
              url: "http://www.ensembl.org/Homo_sapiens/Gene/Summary?g={target_id}"
        pval:
          plot:
            heatmap:
              scale: linear
              range:
                - "#a1d99b"
                - "white"
                - "#fdae6b"
              domain:
                - 0
                - 0.05
                - 0.25
        qval:
          plot:
            heatmap:
              scale: linear
              range:
                - "#a1d99b"
                - "white"
                - "#fdae6b"
              domain:
                - 0
                - 0.05
                - 0.25
        test_stat:
          display-mode: hidden 
        rss:
          display-mode: hidden   
        degrees_free:
          display-mode: hidden
        mean_obs:
          display-mode: hidden
        var_obs:
          display-mode: hidden
        tech_var:
          display-mode: hidden
        sigma_sq:
          display-mode: hidden
        smooth_sigma_sq:
          display-mode: hidden
        final_sigma_sq:
          display-mode: hidden
        regex('qval_.+'):
          display-mode: hidden
        ?f"regex('signed_pi_value_{params.primary_variable}.+')":
          display-mode: normal
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -1
                - 0
                - 1
        ?f"regex('signed_pi_value_(?!{params.primary_variable})')":
          display-mode: hidden # Hide all signed pi cols that are not associated to the primary variable
        ?f"regex('^b_(?!.*_se$)')":
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -10
                - 0
                - 10
        regex('^b_.*_se$'):
          display-mode: hidden
        ?for sample in params.samples:
          ?sample:
            display-mode: hidden
  genes_aggregated:
    dataset: genes_aggregated
    desc: |
      Differentially expressed genes computed with sleuth. The columns `b_*` and `b_*_se` display the effect size `:math:\beta` and the corresponding standard error for every covariate in the model. They are analog to log2 fold changes. Note that non-binary covariates are binarized by sleuth, leading  to multiple columns `b_*1`, `b_*2`, etc.
    page-size: 25
    render-table:
      columns:
        target_id:
          display-mode: normal
        ext_gene:
          display-mode: normal
        gene_desc:
          display-mode: normal
        num_aggregated_transcripts:
          display-mode: normal
        sum_mean_obs_counts:
          display-mode: normal
        pval:
          plot:
            bars:
              scale: linear
              domain:
                - 0.0
                - 1.0
        qval:
          plot:
            bars:
              scale: linear
              domain:
                - 0.0
                - 1.0
        ?for sample in params.samples:
          ?sample:
            display-mode: hidden
  logcount_matrix:    
    dataset: logcount_matrix
    desc: |
        Transcript expression matrix (transcript x samples) as normalized and batch-corrected log counts. Expressions are normalized and corrected for batch effects with the model ~batch_effect, while protecting the model, using Limma.
    page-size: 25
    render-table:
      columns:
        transcript:
          display-mode: normal
        gene:
          display-mode: normal
        ?for sample in params.samples:
          ?sample:
            display-mode: normal
            plot:
              heatmap:
                scale: linear
                range:
                  - "#e6550d"
                  - "white"
                  - "#6baed6"
                domain:
                  - -1
                  - 0
                  - 1
  tpm_matrix:
    dataset: tpm_matrix
    desc: |
      Transcript expression matrix (transcript × samples) as TPM values. TPMs are extracted from Sleuth’s normalized abundance estimates without batch correction, to preserve comparability across independent runs.
    page-size: 25
    render-table:
      columns:
        transcript:
          display-mode: normal
          link-to-url:
            Ensembl:
              url: "http://www.ensembl.org/Homo_sapiens/Gene/Summary?g={value}"
        gene:
          display-mode: normal
        ?for sample in params.samples:
          ?sample:
            display-mode: normal
            ellipsis: 0
            plot:
              heatmap:
                scale: symlog
                range:
                  - "white"
                  - "#e6550d"
