__use_yte__: true

name: ?f"Gene ontology (GO) term enrichment analysis performed by goatools {wildcards.model}"
datasets:
  go_enrichment:
    path: ?input.enrichment
    offer-excel: ?params.offer_excel
    separator: "\t"
default-view: go_enrichment
views:
  go_enrichment:
    dataset: go_enrichment
    desc: |
      Gene ontology (GO) term enrichment analysis was performed with goatools on differentially expressed genes as determined by the sleuth model.
      The resulting table includes several columns with key information and is sorted by the 'p_uncorrected' column in ascending order. The "term" column lists the specific GO term, while the "class" column indicates the classification of the GO term. The "ratio_differential" column shows the ratio of differentially expressed genes within each GO term. The "ratio_size" column provides the ratio of the GO term size relative to the total number of measured genes. Lastly, the "study_items" column details the ratio of genes corresponding to each term, with the option to click on a "+" to see more specific information. This analysis helps to identify and understand the biological significance of gene expression changes.
    page-size: 25
    render-table:
      columns:
        GO:
          display-mode: hidden
          link-to-url: 
            geneontology: 
              url: http://amigo.geneontology.org/amigo/term/{GO}
        class:
          display-mode: normal 
          plot:
            heatmap:
              scale: ordinal
              color-scheme: tableau20
        term:
            link-to-url:
              geneontology:
                url: "http://amigo.geneontology.org/amigo/term/{GO}"
        ratio_in_study:
          display-mode: hidden
        ratio_in_pop:
          display-mode: hidden
        enrichment:
          label: enrichment
          display-mode: normal
          custom-plot:
            data: |
              function(value, row) {
                var parts = value.match(/\((-?\d+\.\d+), (-?\d+\.\d+)\)/);
                if (parts) {
                  var x = parseFloat(parts[1]);
                  var y = parseFloat(parts[2]);
                  return [{"category": "ratio_differential", "amount": x}, {"category": "ratio_size", "amount": y}];
                } else {
                  return "";
                }
              }
            spec-path: ?input.vega_bars
            vega-controls: true
        p_uncorrected:
          label: p-value
          plot:
            heatmap:
              scale: linear
              range:
                - "#2ca02c"
                - "#bcbd22"
              domain:
                - 0.0
                - 1.0            
        depth:
          display-mode: hidden
          plot:
            heatmap:
              scale: linear
        study_count:
          display-mode: hidden
          plot:
            heatmap:
              scale: linear
        p_fdr_bh:
          label: FDR
          plot:
            heatmap:
              scale: linear
              range:
                - "#2ca02c"
                - "#bcbd22"
              domain:
                - 0.0
                - 1.0   
        study_items: 
          display-mode: detail 
          custom-plot:
            data: |
              function customFunction(value, row) {
                if (value && value.trim() !== "") {
                    var geneValues = value.split(', ');
                    var data = [];
                    geneValues.forEach(function(geneValue) {
                      var parts = geneValue.split(':');
                      var gene = parts[0];
                      var val = parseFloat(parts[1]);

                      data.push({"gene": gene, "value": val});
                  });
                  return data;
                } else {
                    return "";
                }
              }  
            spec-path: ?input.vega_waterfall
            vega-controls: true
