name: ?f"Gene ontology (GO) term enrichment analysis performed by goatools {wildcards.model}"
datasets:
  # significant_terms:
  #   path: ?input.significant_terms
  #   offer-excel: true
  #   separator: "\t"
  go_enrichment:
    path: ?input.enrichment
    offer-excel: true
    separator: "\t"
default-view: go_enrichment
views:
  # significant_terms:
  #   dataset: significant_terms
  #   desc: |
  #       Gene ontology (GO) term enrichment analysis performed by goatools, using the sleuth model. Table contains top significant terms of FDR <0.05
  #       The table contains the following columns. "GO" is the GO ID, "term" is the term associated with the GO, "class" is the corresponding class to which the GO term belongs (biological process/cellular component/molecular function), "p-value" is the p-value obtained, "p_corrected" is the corrected p-value, "n_genes_diff_exp" is the number of differentialy expressed genes that belongs to the particular GO term, "n_genes_diff_exp_study" is the total number of differentially expressed genes in the current study, "n_go_genes" is the total number of genes associated with the particular GO term, "gene_ratio" gives the ratio of genes corresponding to each GO term.
  #   page-size: 10
  #   render-table:
  #     columns:
  #       GO:
  #         display-mode: normal
  #         link-to-url: 
  #           geneontology:
  #             url: http://amigo.geneontology.org/amigo/term/{GO}
  #       term:
  #         display-mode: normal
  #       class:
  #         plot:
  #           heatmap:
  #             scale: ordinal
  #       p-value:
  #         plot:
  #           bars:
  #             scale: linear
  #             domain:
  #               - 0.0
  #               - 1.0
  #       p_corrected:
  #         plot:
  #           bars:
  #             scale: linear
  #             domain:
  #               - 0.0
  #               - 1.0
  #       n_genes_diff_exp:
  #         plot:
  #           heatmap:
  #             scale: linear
  #       n_genes_diff_exp_study:
  #         display-mode: normal
  #       n_go_genes:
  #         plot:
  #           bars:
  #             scale: linear
  #       gene_ratio:
  #         plot:
  #           heatmap:
  #             scale: linear
  #       study_items:
  #         display-mode: normal
  go_enrichment:
    dataset: go_enrichment
    desc: |
      <div">
        <p>
          Gene ontology (GO) term enrichment analysis performed by goatools, using the sleuth model. 
          The table contains the following columns:
        </p>
        <div>
          <table border="1" cellpadding="5" cellspacing="0">
              <tr>
                  <td><strong>Column Name</strong></th>
                  <td><strong>Description</strong></th>
              </tr>
              <tr>
                  <td>term</td>
                  <td>Term associated with the GO</td>
              </tr>
              <tr>
                  <td>class</td>
                  <td>GO term class</td>
              </tr>
              <tr>
                  <td>ratio_differential</td>
                  <td>Ratio of differentially expressed genes in the GO term</td>
              </tr>
              <tr>
                  <td>ratio_size</td>
                  <td> Ratio of GO term size in relation to total number of measured genes</td>
              </tr>
              <tr>
                  <td>study_items</td>
                  <td>Ratio of genes corresponding to each term (Click on the "+" to see it)</td>
              </tr>
          </table>
        </div>
      </div>

    page-size: 25
    render-table:
      # add-columns:
      #   test_term:
      #     value: |
      #       function getTerm(row) {
      #         return row.term;
      #       }
      #     link-to-url:
      #       geneontology:
      #         url: "http://amigo.geneontology.org/amigo/term/{GO}"
      # add-columns:
      #   birth_season:
      #     value: |
      #       function getSeasonEmoji(row) {
      #           var month = row.birth_mo;
      #           const seasons = ["❄️", "🌸", "☀️", "🍁"];
      #           return (month < 1 || month > 12) ? "Invalid month" : seasons[Math.floor((month % 12) / 3)];
      #       }


      columns:
        GO:
          display-mode: hidden
          link-to-url: 
            geneontology: 
              url: http://amigo.geneontology.org/amigo/term/{GO}
        class:
          display-mode: normal 
          plot:
            heatmap:
              scale: ordinal
              color-scheme: tableau20
        term:
            link-to-url:
              geneontology:
                url: "http://amigo.geneontology.org/amigo/term/{GO}"
        ratio_in_study:
          # display-mode: normal
          label: ratio_differential
          display-mode: normal
          custom-plot:
            data: |
              function(value, row) {
                var parts = value.match(/\((\d+), (\d+)\)/);
                if (parts) {
                  var x = parseInt(parts[1]);
                  var y = parseInt(parts[2]);
                  return [{"category": "n_genes_diff_exp", "amount": x, "percentage": x/y}, {"category": "n_genes_diff_exp_study", "amount": y, "percentage": x/y}];
                } else {
                  return "";
                }
              }
            spec-path: ?input.vega_circle
            vega-controls: false
        ratio_in_pop:
          label: ratio_size
          # display-mode: normal
          display-mode: normal
          custom-plot:
            data: |
              function(value, row) {
                var parts = value.match(/\((\d+), (\d+)\)/);
                if (parts) {
                  var x = parseInt(parts[1]);
                  var y = parseInt(parts[2]);
                  return [{"category": "n_genes_diff_exp", "amount": x, "percentage": x/y}, {"category": "n_genes_diff_exp_study", "amount": y, "percentage": x/y}];
                } else {
                  return "";
                }
              }
            spec-path: ?input.vega_circle
            vega-controls: false
        p_uncorrected:
          label: p-value
          plot:
            heatmap:
              scale: linear
              range:
                - "#2ca02c"
                - "#bcbd22"
              domain:
                - 0.0
                - 1.0            
        depth:
          display-mode: hidden
          plot:
            heatmap:
              scale: linear
        study_count:
          display-mode: hidden

          plot:
            heatmap:
              scale: linear
        p_fdr_bh:
          label: FDR
          plot:
            heatmap:
              scale: linear
              range:
                - "#2ca02c"
                - "#bcbd22"
              domain:
                - 0.0
                - 1.0   
        study_items: 
          display-mode: hidden
        study_items_sig_terms:
          label: study_items
          display-mode: detail 
          custom-plot:
            data: |
              function customFunction(value, row) {
                if (value && value.trim() !== "") {
                    var geneValues = value.split(', ');
                    var data = [];
                    console.log("Values", value)
                    geneValues.forEach(function(geneValue) {
                      var parts = geneValue.split(':');
                      var gene = parts[0];
                      var val = parseFloat(parts[1]);
                      console.log("Gene", gene, "value", val)

                      data.push({"gene": gene, "value": val});
                  });
                  return data;
                } else {
                    return "";
                }
              }  
            spec-path: ?input.vega_waterfall
            vega-controls: true
