__use_yte__: true

name: ?f"Inputs used to start the pipeline"
datasets:
  samples:
    path: ?input.samples
    offer-excel: ?params.offer_excel
    separator: "\t"
  units:
    path: ?input.units
    offer-excel: ?params.offer_excel
    separator: "\t"
default-view: samples
views:
  samples:
    dataset: samples
    desc: |
      Samples.tsv as given
    page-size: 25
    render-table:
      columns:
  units:
    dataset: units
    desc: |
      units.tsv as given
    page-size: 25
    render-table:
      columns: