__use_yte__: true

name: ?f"Meta comparison for {wildcards.meta_comp}"
datasets:
  comparison_table:
    path: ?input.table
    offer-excel: true
    separator: "\t"
default-view: comparison_plot
views:
  comparison_table:
    dataset: comparison_table
    desc: |
      Table for values of meta comparison
    page-size: 25
    render-table:
      columns:
        ext_gene:
          display-mode: normal       
        min q-value:
          plot:
            heatmap:
              scale: linear
              range:
                - "#a1d99b"
                - "white"
                - "#fdae6b"
              domain:
                - 0
                - 0.05
                - 0.25
        effect mgl (beta score):
          display-mode: normal
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -8
                - 0
                - 8
        effect t3 (beta score):
          display-mode: normal
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -8
                - 0
                - 8
  comparison_plot:
    desc: |
      The axes represent the log2-fold changes (beta-scores) for the two models, with each point representing a gene. Points on the diagonal indicate no difference between the comparisons, while deviations from the diagonal suggest differences in gene expression fold changes between the treatments.
    dataset: comparison_table
    render-plot:
      spec-path: ?input.plot