name: ?f"Meta comparison for {wildcards.meta_comp}"
datasets:
  comparison_table:
    path: ?input.table
    offer-excel: true
    separator: "\t"
default-view: comparison_plot
views:
  comparison_table:
    dataset: comparison_table
    desc: |
      Table for values of meta comparison
    page-size: 25
    render-table:
      columns:
        Name:
          display-mode: normal       
        min fdr:
          display-mode: normal
          plot:
            heatmap:
              scale: linear
              color-scheme: greens
        effect mgl:
          display-mode: normal
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -300
                - 0
                - 300
        effect t3:
          display-mode: normal
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -300
                - 0
                - 300
  comparison_plot:
    desc: |
       The effect is shown as the "total net accumulated perturbation," indicating the extent to which a pathway is activated (positive) or inhibited (negative) by the differential genes, with each point representing a pathway. Points on the diagonal indicate no difference between the two comparisons, highlighting potential differences when they deviate from this line.
    dataset: comparison_table
    render-plot:
      spec-path: ?input.plot