__use_yte__: true

name: ?f"Inputs used to start the pipeline"
datasets:
  samples:
    path: ?input.table
    offer-excel: ?params.offer_excel
    separator: "\t"
default-view: samples
views:
  samples:
    dataset: samples
    desc: |
      samples.tsv given as input
    page-size: 25