name: ?f"spia pathway impact analysis for model {wildcards.model}"
datasets:
  spia_table:
    path: ?input.spia_table
    offer-excel: true
    separator: "\t"
default-view: spia_table
views:
  spia_table:
    dataset: spia_table
    desc: |


      <div">
        <p>
          Spia pathway impact analysis
        </p>
        <div>
          <table border="1" cellpadding="5" cellspacing="0">
              <tr>
                  <td><strong>Column Name</strong></th>
                  <td><strong>Description</strong></th>
              </tr>
              <tr>
                  <td>Name</td>
                  <td>The name of the pathway being investigated in the analysis</td>
              </tr>
              <tr>
                  <td>total perturbation accumulation</td>
                  <td>Quantifies the total perturbation or disruption occurring in the pathway</td>
              </tr>
              <tr>
                  <td>Status</td>
                  <td>Reflects the activity or response of the pathway</td>
              </tr>
              <tr>
                  <td>gene_ratio</td>
                  <td>Ratio of genes present in the pathway under consideration compared to the total number of genes in the analyzed genome</td>
              </tr>
              <tr>
                  <td>pathway id</td>
                  <td>Unique identification number for the pathway under consideration</td>
              </tr>
          </table>
        </div>
      </div>
    page-size: 25
    render-table:
      columns:
        Name:
          display-mode: normal
          link-to-url: 
            pathway:
              ?if params.pathway_db == "reactome":
                url: "http://reactome.org/PathwayBrowser/#/{pathway id}"
              ?elif params.pathway_db == "panther":
                url: "https://www.pantherdb.org/pathway/pathwayDiagram.jsp?catAccession={pathway id}"
              # we should add all the pathway databases that bioconductor-graphite enables (see its `pathwayDatabases()` function)
              ?else: # not sure what a good fallback would be here
                url: "http://reactome.org/PathwayBrowser/#/{pathway id}"
        number of genes on the pathway:
          display-mode: hidden
          # label: "number of genes"
          # plot:
          #   heatmap:
          #     scale: linear
          #     range:
          #       - "#F7F7F7"
          #       - "#B2182B"
        number of DE genes per pathway:
          display-mode: hidden
          # label: "number of DE genes"
          # plot:
          #   heatmap:
          #     scale: linear
          #     range:
          #       - "#F7F7F7"
          #       - "#B2182B"
        gene_ratio:
          custom-plot:
            data: |
              function(value, row) {
                var parts = value.match(/\((\d+), (\d+)\)/);
                if (parts) {
                  var x = parseInt(parts[1]);
                  var y = parseInt(parts[2]);
                  return [{"category": "DE_genes", "amount": x, "percentage": x/y}, {"category": "genes", "amount": y, "percentage": x/y}];
                } else {
                  return "";
                }
              }
            spec-path: ?input.vega_circle
            vega-controls: false
        p-value for at least NDE genes:
          display-mode: detail
        total perturbation accumulation:
          plot:
            heatmap:
              scale: linear
              range:
                - "#B2182B"
                - "#F7F7F7"
                - "#2166AC"
              domain-mid: 0
        p-value to observe a total accumulation:
          display-mode: detail
        Combined p-value:
          display-mode: detail
        Combined FDR:
          plot:
            heatmap:
              scale: linear
              range:
                - "#2ca02c"
                - "#bcbd22"
              domain:
                - 0.0
                - 1.0  
        Combined Bonferroni p-values:
          display-mode: detail     
        Status:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: accent
        pathway id:
          display-mode: detail