name: ?f"Pathway impact analysis for model {wildcards.model}"
datasets:
  spia_results:
    path: ?input.spia_results
    separator: "\t"
views:
  impacted_pathways:
    dataset: spia_results
    desc: |
        The table contains the following columns pSize is the number of genes on the pathway; NDE is the number of DE genes per pathway; tA is the observed total perturbation accumulation in the pathway; pNDE is the probability to observe at least NDE genes on the pathway using a hypergeometric model; pPERT is the probability to observe a total accumulation more extreme than tA only by chance; pG is the p-value obtained by combining pNDE and pPERT; pGFdr and pGFWER are the False Discovery Rate and respectively Bonferroni adjusted global p-values; and the Status gives the direction in which the pathway is perturbed (activated or inhibited).
    page-size: 25
    render-table:
      columns:
        Name:
          display-mode: normal
          link-to-url: "http://reactome.org/PathwayBrowser/#/{Ids}"
        number of genes on the pathway:
          display-mode: normal
          plot:
            heatmap:
              scale: linear
              range:
                - white
                - "#186904"         
        number of DE genes per pathway:
          display-mode: normal
          plot:
            heatmap:
              scale: linear
              range:
                - white
                - "#186904"
        p-value for at least NDE genes:
          display-mode: hidden
          plot:
            heatmap:
              scale: linear
              range:
                - "#1f77b4"
                - white
        total perturbation accumulation:
          custom: |
            function(value, row) {
              if (value < 0) {
                return `<div style="background-color: #e6550d;">${value}</div>`;
              } else if (value > 0) {
                return `<div style="background-color: #6baed6">${value}</div>`;
              } else {
                return `${value}`;
              }
            }
        p-value to observe a total accumulation:
          display-mode: hidden
          plot:
            heatmap:
              scale: linear
              range:
                - "#1f77b4"
                - white
        Combined p-value:
          display-mode: hidden
          plot:
            heatmap:
              scale: linear
              range:
                - "#1f77b4"
                - white
        Combined FDR:
          plot:
            heatmap:
              scale: linear
              range:
                - "#1f77b4"
                - white
        Combined Bonferroni p-values:
          display-mode: hidden
          plot:
            heatmap:
              scale: linear
              range:
                - "#1f77b4"
                - white         
        Status:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: accent       
        Ids:
          display-mode: hidden
          link-to-url: "http://reactome.org/PathwayBrowser/#/{value}"