__use_yte__: true

name: ?f"Inputs used to start the pipeline"
datasets:
  units:
    path: ?input.units
    offer-excel: ?params.offer_excel
    separator: "\t"
default-view: units
views:
  units:
    dataset: units
    desc: |
      units.tsv given as input
    page-size: 25
    render-table:
      columns:
        unit:
          display-mode: normal 
          plot:
            heatmap:
              scale: ordinal
              color-scheme: blues
        fragment_len_mean:
          display-mode: normal 
          plot:
            heatmap:
              scale: ordinal
              color-scheme: greens
        fragment_len_sd:
          display-mode: normal 
          plot:
            heatmap:
              scale: ordinal
              color-scheme: reds