__use_yte__: true

name: ?f"Inputs used to start the pipeline"
datasets:
  units:
    path: ?input.table
    offer-excel: ?params.offer_excel
    separator: "\t"
default-view: units
views:
  units:
    dataset: units
    desc: |
      units.tsv given as input
    page-size: 25